import './globals.css'
import { Inter } from 'next/font/google'
import StoreProvider from '../../public/RTK/storeProvider'
const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Barter',
  description: 'Generated by Mishal Ahamed FAHAD',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  )
}


