import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from "../Components/Home/navbar"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Berter',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
        <div className="flex justify-center fixed top-2 left-[50%] right-[50%] sm:ml-[-300px]">
          <Navbar />
        </div>
      </body>
    </html>
  )
}






